---
title: "Resultados da avaliação do Curso na UFV"
author: Prof. Walmes M. Zeviani
date: '`r Sys.Date()`'
---

```{r, include = FALSE}
source("./config/setup.R")
opts_chunk$set(
    cache = FALSE,
    message = FALSE,
    warning = FALSE)
```

```{r}
#-----------------------------------------------------------------------

rm(list = objects())

library(tidyverse)
library(RColorBrewer)

# display.brewer.all()

# Importação do questionário.
tb <- read_csv("./data/Avaliacao-do-Curso- GenMelhor-UFV.csv")

#-----------------------------------------------------------------------
# Questões aplicadas.

ques <- names(tb) %>%
    tail(n = -1) %>%
    str_c(1:length(.), ., sep = ". ") %>%
    map(strwrap, width = 50, simplify = TRUE)

# Questões do questionário.
for (i in ques) {
    cat(i, sep = "\n")
    cat("\n")
}

# Elimina a coluna de estampa de tempo.
tb[[1]] <- NULL

nms <- names(tb)
names(tb) <- sprintf("V%d", 1:ncol(tb))

#-----------------------------------------------------------------------
# Para retornar o gráfico de setores.

my_pie <- function(tb, txt) {
    txt <- str_c(strwrap(txt, width = 20), collapse = "\n")
    ggplot(tb_aux,
           aes(x = 0, y = n, fill = lev)) +
        geom_col(color = "black") +
        scale_fill_brewer(name = txt, palette = "PuOr") +
        xlab(NULL) +
        ylab(NULL) +
        geom_text(mapping = aes(x = 0.2, label = label),
                  position = position_stack(vjust = 0.5)) +
        coord_polar(theta = "y") +
        theme_minimal()
}

my_bar <- function(tb, txt) {
    ggplot(tb_aux,
           aes(x = lev, y = n)) +
        geom_col(fill = "purple", color = "black") +
        xlab(txt) +
        ylab("Frequência absoluta") +
        geom_text(mapping = aes(label = label),
                  vjust = -0.2)
}

my_stk <- function(tb, txt) {
    ggplot(tb_aux,
           aes(x = 0,
               y = n,
               fill = fct_relevel(lev,
                                  rev(levels(lev))))) +
        geom_col(color = "black") +
        scale_fill_brewer(name = NULL,
                          palette = "PuOr",
                          direction = -1) +
        xlab(NULL) +
        ylab("Frequência absoluta") +
        geom_text(mapping = aes(x = -0.4,
                                label = sprintf("%s: %s", lev, label)),
                  hjust = 0,
                  position = position_stack(vjust = 0.5)) +
        ggtitle(label = txt) +
        theme_minimal() +
        theme(legend.position = "none") +
        scale_x_continuous(breaks = NULL)
}

my_dot <- function(tb, txt) {
    tb_large <- tb_aux[rep(1:nrow(tb_aux), times = tb_aux$n), ]
    ggplot(tb_large,
           aes(x = lev)) +
        geom_dotplot(color = "black") +
        xlab(txt) +
        ylab(NULL) +
        geom_text(data = tb_aux,
                  mapping = aes(x = lev, y = 0, label = label),
                  vjust = -0.1, hjust = 0, nudge_x = 0.1) +
        scale_y_continuous(NULL, breaks = NULL)
}

# 1. -------------------------------------------------------------------

nms[1]
x <- tb[[1]] %>%
    str_to_upper() %>%
    iconv(to = "ASCII//TRANSLIT") %>%
    sort()
x

u <- c("MESTRADO", "DOUTORADO")
tb_aux <- x %>%
    str_replace_all(sprintf(".*(%s).*",
                            paste(u, collapse = "|")),
                    "\\1") %>%
    factor() %>%
    fct_other(keep = u,
              other_level = "Desconhecido") %>%
    fct_count() %>%
    rename(lev = "f") %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)))

my_pie(tb_aux, "Nível")
# my_bar(tb_aux, "Nível")
# my_dot(tb_aux, "Nível")
# my_stk(tb_aux, "Nível")

u <- c("GENETICA", "ESTATISTICA", "PRODUCAO VEGETAL","FITOPATOLOGIA")
tb_aux <- x %>%
    str_replace_all(sprintf(".*(%s).*",
                            paste(u, collapse = "|")),
                    "\\1") %>%
    factor() %>%
    fct_other(keep = u,
              other_level = "Outro") %>%
    fct_infreq() %>%
    fct_count() %>%
    rename(lev = "f") %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)))

# my_pie(tb_aux, "Programa")
my_bar(tb_aux, "Programa de Pós Graduação")
# my_stk(tb_aux, "Programa de Pós Graduação")

# 2. -------------------------------------------------------------------

nms[2]
ggplot(tb, aes(x = V2)) +
    stat_ecdf() +
    geom_rug() +
    xlab(nms[2]) +
    ylab("Frequência relativa")

# tb_aux <- tb %>%
#     mutate(lev = cut(V2,
#                      breaks = c(0, 1, 2, 5, Inf),
#                      right = TRUE,
#                      include.lowest = TRUE)) %>%
#     count(lev) %>%
#     mutate(label = sprintf("%d\n(%0.1f%%)", n, 100 * n/sum(n)))
# my_pie(tb_aux, nms[2])
# my_bar(tb_aux, nms[2])

bks <- seq(0, max(tb$V2), by = 1)
ggplot(tb, aes(x = V2)) +
    geom_histogram(breaks = bks,
                   col = "black",
                   fill = "purple") +
        ylab("Frequência absoluta") +
    geom_rug() +
    stat_bin(breaks = bks,
             geom = "text",
             aes(label = ..count..),
             vjust = -0.5) +
    xlab(nms[2])

# 3. -------------------------------------------------------------------

i <- 3
nms[i]
lvl <- sort(unique(tb[[i]]))[c(4, 2, 1, 3)]
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(lev, lvl))

# my_pie(tb_aux, txt)
my_dot(tb_aux, txt)

# 4. -------------------------------------------------------------------

i <- 4
nms[i]
lvl <- sort(unique(tb[[i]]))[c(3, 1, 4, 2)]
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(lev, lvl))

# my_pie(tb_aux, txt)
# my_bar(tb_aux, txt)
my_stk(tb_aux, txt)

# 5. -------------------------------------------------------------------

i <- 5
nms[i]
lvl <- sort(unique(tb[[i]]))[c(1, 2, 3)]
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(lev, lvl))

my_pie(tb_aux, txt)
# my_bar(tb_aux, txt)

# 6. -------------------------------------------------------------------

i <- 6
nms[i]
lvl <- sort(unique(tb[[i]]))[c(1, 2, 3)]
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(lev, lvl))

# my_pie(tb_aux, txt)
# my_bar(tb_aux, txt)
my_stk(tb_aux, txt)

# 7. -------------------------------------------------------------------

i <- 7
nms[i]
lvl <- as.character(sort(unique(tb[[i]])))
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(factor(lev), lvl))

# my_pie(tb_aux, txt)
my_bar(tb_aux, txt)

# 8. -------------------------------------------------------------------

i <- 8
nms[i]
lvl <- sort(unique(tb[[i]]))[c(1, 3, 2)]
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(lev, lvl))

my_pie(tb_aux, txt)

# 9. -------------------------------------------------------------------

i <- 9
nms[i]
lvl <- sort(unique(tb[[i]]))[c(2, 1)]
txt <- nms[i]
tb_aux <- tb %>%
    count(lev = tb[[i]]) %>%
    mutate(label = sprintf("%d (%0.1f%%)", n, 100 * n/sum(n)),
           lev = fct_relevel(lev, lvl))

my_pie(tb_aux, txt)

# 10. ------------------------------------------------------------------

nms[10]
tb_aux <- tb[[10]] %>%
    str_replace_all(pattern = ", ([[:upper:]])",
                    replacement = ";\\1") %>%
    str_split(pattern = ";") %>%
    flatten_chr() %>%
    fct_count() %>%
    mutate(lev =
               {
                   as.character(.$f) %>%
                       map(strwrap, width = 15) %>%
                       map_chr(str_c, collapse = "\n") %>%
                       factor()
               },
           lev = fct_reorder(lev, n),
           label = sprintf("%d (%0.1f%%)", n, 100 * n/nrow(tb)))

ggplot(tb_aux,
       aes(x = lev, y = n)) +
    geom_col(color = "black", fill = "purple") +
    xlab("Cursos a serem realizados") +
    ylab("Frequência absoluta") +
    geom_text(mapping = aes(label = label),
              vjust = 0,
              nudge_y = 0.2)

# 11. ------------------------------------------------------------------

nms[11]

x <- tb[[11]]
x <- x[order(nchar(x))]

comm <- x %>%
    str_c(1:length(.), ., sep = ". ") %>%
    map(strwrap, width = 60, simplify = TRUE)

# # Questões do questionário.
# for (i in comm) {
#     cat(i, sep = "\n")
#     cat("\n")
# }
```

```{r, results = "asis"}
comm %>%
    map_chr(str_c, collapse = " ") %>%
    str_c("  ", .) %>%
    cat(sep = "\n")
```
