---
title: "Manipulação e Visualização de Dados"
subtitle: >
  <p><span style = "font-size: 120%;">A abordagem <code style = "font-size: 105%;">tidyverse</code></span></p>
author: >
  <br>
  <br>
  Prof. <a href="http://www.leg.ufpr.br/~walmes">Walmes Marques Zeviani</a><br>
  Laboratório de Estatística e Geoinformação (LEG) <a href="leg.ufpr.br"><i class="fa fa-external-link fa-xs fa-xs"></i></a><br>
  Departamento de Estatística (DEST) <a href="http://www.est.ufpr.br"><i class="fa fa-external-link fa-xs"></i></a><br>
  Universidade Federal do Paraná (UFPR) <a href="http://www.ufpr.br"><i class="fa fa-external-link fa-xs"></i></a>
bibliography: config/refs.bib
csl: config/ABNT-UFPR-2011-Mendeley.csl
output:
  html_document:
    toc: false
    number_sections: false
    includes:
      before_body: config/site-header.html
      after_body: config/site-footer.html
---

```{r, include = FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

<!--
<div class="alert alert-info" role="alert">
<center>
<a href="https://docs.google.com/forms/d/e/1FAIpQLSdKiXXUlP9n4MKUczhrx6RjVZa7eYebN4ST3V99hzAHTtceOA/viewform?usp=sf_link">
Formulário de Avaliação do Curso
</a>
</center>
</div>
-->

# Resumo

A maior parte do esforço na análise de dados está na manipulação dos
dados: leitura, preparo, higienização, imputação, aprimoramento,
seleção, agregação, síntese e visualização. O ambiente R para computação
estatística e gráficos, como linguagem de programação, dipõe recursos
para manipulação de dados desde as primeiras versões. A recente
abordagem [`tidyverse`], no entanto, se baseia em uma gramática clara
para a manipulação de dados, o que reduz o tempo de confecção e
entendimento de instruções de código, tornando-o mais portável e
reproduzível. Em vários aspectos, também tem melhor performance
computacional. Nesse Curso, é abordado o uso coordenado de pacotes da
coleção [`tidyverse`], com ênfase nos seus principais recursos para
manipulação e visualização de dados. Exemplos baseados em conjuntos de
dados reais e scripts R são disponibilizados.

A visualização permite rápida extração de *insights* de problemas
baseados em dados. É a língua nativa para comunicação de padrões,
tendências e fatos dos dados para humanos e entre humanos. Inúmeros
softwares e planilhas eletrônicas oferecem recursos para confecção de
gráficos. Ainda que haja tal disponibilidade, são vistos com frequência
representações de má qualidade no âmbito profissional e acadêmico. Dessa
forma, o conhecimento dos princípios de visualização gráfica e o domínio
de recursos computacionais para elaboração ágil, interativa e
reproduzível são fundamentais para obter visualizações que comuniquem
valor de forma descomplicada em todos os aspectos: elaboração, leitura e
interpretação. Esse Curso também são discutidos fundamentos da
visualização de dados e sua aplicação no ambiente R. A ênfase é tanto
instrumentar o uso coordenado de pacotes e funções do R como também
desenvolver massa crítica para construção e apreciação de representações
gráficas de dados.

# Conteúdo

  1. Revisão de princípios de programação em R.
  2. Manipulação de dados com `tidyverse`.
     1. A organização lógica e filosófica do `tidyverse`.
     2. Importação, represetação e exportação de dados.
     3. Organização e limpeza de dados.
     4. Manipulação de dados.
     5. Análise descritiva.
     6. Tratatamento de strings e fatores.
  3. Recursos gráficos estáticos e interativos.
     1. Princípios de visualização de dados.
     2. Recusos para visualização estática.
     3. Recursos para visualização dinâmica.
  4. Programação funcional.
  5. Introdução aos relatórios dinâmicos.

# Realizações do Curso {.tabset}

## V2.2: GemMelhor-UFV

  * Organização: [GenMelhor UFV](https://www.genmelhor.com.br/).
  * Público: Alunos de Pós Graduação.
  * Instrutor: Prof. Walmes M. Zeviani.
  * Local: Laboratório de Biometria - Departamento de Biologia Geral.
  * Período: 18 a 21 de Março de 2019 das 10h às 12h e 14h às 17h.
  * Carga horária: 20 horas.

## V2.0: DES-UFLA

  * Organização: [X Programa de Verão DES/UFLA](http://www.des.ufla.br/eventos/programa-de-verao-2019).
  * Público: Alunos do Programa de [Pós Graduação em Estatística e Experimentação Agropecuária](http://prpg.ufla.br/_ppg/estatistica/), UFLA.
  * Instrutor: Prof. Walmes M. Zeviani.
  * Local: DEX-13.
  * Período: 12 de Março de 2019 das 9h às 11h e 14h às 16h.
  * Carga horária: 4 horas.

## V1.0: GEN-UFLA

  * Organização: [Núcleo de Estudos em Genética e Melhoramento de Plantas](http://www.nucleoestudo.ufla.br/gen/)
  * Público: Alunos do Programa de [Pós Graduação em Genética e Melhoramento de Plantas](http://prpg.ufla.br/_ppg/genetica/), UFLA.
  * Instrutor: Prof. Walmes M. Zeviani.
  * Carga horária: 15 horas.

  | Local       | Terça 07/08/2018 | Quarta 08/08 | Quinta 09/08 |
  |:-----------:|:----------------:|:------------:|:------------:|
  | PV3 sala 06 |                  | 09h -- 12h   | 09h -- 12h   |
  | PV3 sala 06 | 14h -- 17h       | 14h -- 17h   | 14h -- 17h   |

# Materiais úteis

  1. Livros online:
     1. [R for Data Science](http://r4ds.had.co.nz/).
     2. [Statistical Inference via Data Science](https://moderndive.com/).
     3. [Advanced R](https://adv-r.hadley.nz/).
     4. [Efficient R Programming](https://csgillespie.github.io/efficientR/).
     5. [Hands-On Programming with R](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf).
  2. Homepages:
     1. [`tidyverse`](https://www.tidyverse.org/).
     2. [`ggplot2`](https://ggplot2.tidyverse.org/).
     3. [`lattice`](http://lmdvr.r-forge.r-project.org/figures/figures.html).
     4. [`latticeExtra`](http://latticeextra.r-forge.r-project.org/).
  3. Materiais de cursos:
     1. [Introduction to the R tidyverse - Erik Barry Erhardt](https://statacumen.com/teach/ShortCourses/R_Programming/IntroTidyverse_ACASA_201802/Erhardt_RTidyverse_20180216.pdf).
     2. [An Introduction to Tidyverse - Joey Stanley](http://joeystanley.com/downloads/171110-tidyverse_handout.pdf).
     3. [A Two Hour Tour of the Tidyverse - Aimee Gott](https://www.londonr.org/wp-content/uploads/sites/2/presentations/LondonR_-_A_tour_of_the_Tidyverse_-_Aimee_Gott_-_20170515.pdf).
     4. [Dplyr Introduction - Matthew Flickinger](https://genome.sph.umich.edu/w/images/8/8a/Dplyr_tidyverse_md.pdf).
     5. [Getting Started in R: Tidyverse Edition - Saghir Bashir](http://ilustat.com/shared/Getting-Started-in-R.pdf).
     6. [Introduction à R et au tidyverse - Julien Barnier](https://www.ecofog.gf/IMG/pdf/introduction_au_tidyverse.pdf).
     7. [The tidyverse style guide - Hadley Wickham](https://style.tidyverse.org/_main.pdf).
     8. [Une introduction à Tidyverse - Christophe Ambroise](http://www.math-evry.cnrs.fr/_media/members/cambroise/teaching/r4ds-slides.pdf).
     9. [Hadley Wickham - ggplot: Elegant graphics for data analysis](http://moderngraphics11.pbworks.com/f/ggplot2-Book09hWickham.pdf).
     10. [Data Visualization Using R & ggplot - Karthik Ram](https://combine-australia.github.io/r-novice-gapminder/ggplot.pdf).
     11. [A ggplot2 Primer](https://www.data-action-lab.com/wp-content/uploads/2018/11/DSRS_GGP2.pdf).
     12. [ggplot2: Introduction and exercises - Umer Zeeshan Ijaz](http://userweb.eng.gla.ac.uk/umer.ijaz/bioinformatics/ecological/ggplot2.pdf).
     13. [Getting started with ggplot2 - Gaston Sanchez](https://github.com/ucb-stat133/stat133-fall-2016/blob/master/notes/09-ggplot2/09-ggplot2.pdf).
     14. [Concepts in Computing with Data - Gaston Sanchez](http://www.gastonsanchez.com/stat133/lectures/).
     15. [STAT 408](http://www.math.montana.edu/ahoegh/teaching/stat408/lecturematerials/).
     16. [Charts with ggplot2 -Andrew Ba Tran](https://journalismcourses.org/courses/RC0818/charts_with_ggplot.pdf).
  4. Folhas de referência (*cheatsheets*):
     1. [R Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf).
     2. [Base R](http://github.com/rstudio/cheatsheets/raw/master/base-r.pdf).
     3. [Advanced R](https://www.rstudio.com/wp-content/uploads/2016/02/advancedR.pdf).
     4. [Data import](https://github.com/rstudio/cheatsheets/raw/master/data-import.pdf).
     5. [Data transformation](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf).
     6. [Data visualization](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf).
     7. [R Markdown](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf).
     8. [Data Wranglingwith dplyr and tidyr](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf).
     9. [`data.table`](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/datatable_Cheat_Sheet_R.pdf).

# Referências bibliográficas

  * WICKHAM, H. & GROLEMUND, G. [**R for Data Science**](http://r4ds.had.co.nz/). Sebastopol: O'Reilly, 2016.
  * WICKHAM, H. [**ggplot2: elegant graphics for data analysis**](https://ggplot2.tidyverse.org/). Dordrecht New York: Springer, 2009.
  * SARKAR, D. [**Lattice: multivariate data visualization with R**](http://lmdvr.r-forge.r-project.org/figures/figures.html). New York London: Springer Science+Business Media, 2008.
  * GILLESPIE, C., & LOVELACE, R. [**Efficient R programming: a practical guide to smarter programming**](https://csgillespie.github.io/efficientR/). Sebastopol, CA: O'Reilly Media, 2016.
  * WICKHAM, H. [**Advanced R**](https://adv-r.hadley.nz/). Boca Raton, FL: CRC Press, 2015.

<!------------------------------------------- -->
[`tidyverse`]: https://www.tidyverse.org/
